version: '3.7'

services:
  goassets:
    container_name: go_assets
    build: .
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - goassets-mysql

  goassets-mysql:
    image: mysql:5.7
    container_name: go_assets_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=${DATABASE_HOST}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    restart: unless-stopped
    volumes:
      - database_mysql:/var/lib/mysql

volumes:
  database_mysql: